linters:
  disable-all: true
  enable:
    - bodyclose
    - godox
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace
